#!/bin/sh
chmod 644 /usr/share/applications/hildon/CSSUfeatures.desktop
chmod 644 /etc/sudoers.d/CSSUfeatures.sudoers
python3 -m compileall /opt/CSSUfeatures/
rm /opt/CSSUfeatures/*.py
chmod 644 /opt/CSSUfeatures/*
chmod 755 /opt/CSSUfeatures/CSSU_Features_Configuration
chmod 744 /opt/CSSUfeatures/updateTransitions
chmod 644 /usr/share/hildon-desktop/transitions.ini.default
chown root /opt/CSSUfeatures/*
chown root /usr/share/applications/hildon/CSSUfeatures.desktop
chown root /etc/sudoers.d/CSSUfeatures.sudoers
chown root /usr/share/hildon-desktop/transitions.ini.default
if [ -d /home/user/.CSSUfeatures/ ]
then
   rm -rf /home/user/.CSSUfeatures/*
fi
gtk-update-icon-cache -f /usr/share/icons/hicolor
#update-sudoers
ln -s /opt/CSSUfeatures/CSSUfeatures.xml /etc/systemui/CSSUfeatures.xml
killall systemui
