# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Backups_common\pythonExamples\maemo\CSSUfeatures\CSSUfeaturesUI.ui'
#
# Created: Wed Sep 07 23:35:12 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_CSSUfeaturesUI(object):
    def setupUi(self, CSSUfeaturesUI):
        CSSUfeaturesUI.setObjectName(_fromUtf8("CSSUfeaturesUI"))
        CSSUfeaturesUI.resize(800, 450)
        font = QtGui.QFont()
        font.setPointSize(12)
        CSSUfeaturesUI.setFont(font)
        self.centralwidget = QtGui.QWidget(CSSUfeaturesUI)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSpacing(2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.scrollArea = QtGui.QScrollArea(self.centralwidget)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignCenter)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -525, 761, 1080))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 1080))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_4 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setHorizontalSpacing(6)
        self.gridLayout_2.setVerticalSpacing(2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.comboBoxBlurless = QtGui.QComboBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxBlurless.sizePolicy().hasHeightForWidth())
        self.comboBoxBlurless.setSizePolicy(sizePolicy)
        self.comboBoxBlurless.setMinimumSize(QtCore.QSize(0, 55))
        self.comboBoxBlurless.setMaximumSize(QtCore.QSize(16777215, 55))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.comboBoxBlurless.setFont(font)
        self.comboBoxBlurless.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBoxBlurless.setMaxVisibleItems(2)
        self.comboBoxBlurless.setMaxCount(2)
        self.comboBoxBlurless.setObjectName(_fromUtf8("comboBoxBlurless"))
        self.comboBoxBlurless.addItem(_fromUtf8(""))
        self.comboBoxBlurless.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.comboBoxBlurless, 0, 1, 1, 1)
        self.label_02 = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_02.sizePolicy().hasHeightForWidth())
        self.label_02.setSizePolicy(sizePolicy)
        self.label_02.setMinimumSize(QtCore.QSize(0, 0))
        self.label_02.setMaximumSize(QtCore.QSize(16777215, 55))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(50)
        font.setBold(False)
        self.label_02.setFont(font)
        self.label_02.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_02.setObjectName(_fromUtf8("label_02"))
        self.gridLayout_2.addWidget(self.label_02, 2, 0, 1, 1)
        self.comboBoxTaskSwitcher = QtGui.QComboBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxTaskSwitcher.sizePolicy().hasHeightForWidth())
        self.comboBoxTaskSwitcher.setSizePolicy(sizePolicy)
        self.comboBoxTaskSwitcher.setMinimumSize(QtCore.QSize(0, 55))
        self.comboBoxTaskSwitcher.setMaximumSize(QtCore.QSize(16777215, 55))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.comboBoxTaskSwitcher.setFont(font)
        self.comboBoxTaskSwitcher.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBoxTaskSwitcher.setMaxVisibleItems(3)
        self.comboBoxTaskSwitcher.setMaxCount(3)
        self.comboBoxTaskSwitcher.setObjectName(_fromUtf8("comboBoxTaskSwitcher"))
        self.comboBoxTaskSwitcher.addItem(_fromUtf8(""))
        self.comboBoxTaskSwitcher.addItem(_fromUtf8(""))
        self.comboBoxTaskSwitcher.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.comboBoxTaskSwitcher, 2, 1, 1, 1)
        self.label_03 = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_03.sizePolicy().hasHeightForWidth())
        self.label_03.setSizePolicy(sizePolicy)
        self.label_03.setMinimumSize(QtCore.QSize(0, 0))
        self.label_03.setMaximumSize(QtCore.QSize(16777215, 55))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(50)
        font.setBold(False)
        self.label_03.setFont(font)
        self.label_03.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_03.setObjectName(_fromUtf8("label_03"))
        self.gridLayout_2.addWidget(self.label_03, 5, 0, 1, 1)
        self.comboBoxRotationAxis = QtGui.QComboBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxRotationAxis.sizePolicy().hasHeightForWidth())
        self.comboBoxRotationAxis.setSizePolicy(sizePolicy)
        self.comboBoxRotationAxis.setMinimumSize(QtCore.QSize(0, 55))
        self.comboBoxRotationAxis.setMaximumSize(QtCore.QSize(16777215, 55))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.comboBoxRotationAxis.setFont(font)
        self.comboBoxRotationAxis.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBoxRotationAxis.setMaxVisibleItems(2)
        self.comboBoxRotationAxis.setMaxCount(2)
        self.comboBoxRotationAxis.setObjectName(_fromUtf8("comboBoxRotationAxis"))
        self.comboBoxRotationAxis.addItem(_fromUtf8(""))
        self.comboBoxRotationAxis.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.comboBoxRotationAxis, 5, 1, 1, 1)
        self.label_04 = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_04.sizePolicy().hasHeightForWidth())
        self.label_04.setSizePolicy(sizePolicy)
        self.label_04.setMinimumSize(QtCore.QSize(0, 0))
        self.label_04.setMaximumSize(QtCore.QSize(16777215, 55))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(50)
        font.setBold(False)
        self.label_04.setFont(font)
        self.label_04.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_04.setObjectName(_fromUtf8("label_04"))
        self.gridLayout_2.addWidget(self.label_04, 6, 0, 1, 1)
        self.comboBoxForcedRotation = QtGui.QComboBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxForcedRotation.sizePolicy().hasHeightForWidth())
        self.comboBoxForcedRotation.setSizePolicy(sizePolicy)
        self.comboBoxForcedRotation.setMinimumSize(QtCore.QSize(0, 55))
        self.comboBoxForcedRotation.setMaximumSize(QtCore.QSize(16777215, 55))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.comboBoxForcedRotation.setFont(font)
        self.comboBoxForcedRotation.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBoxForcedRotation.setMaxVisibleItems(2)
        self.comboBoxForcedRotation.setMaxCount(2)
        self.comboBoxForcedRotation.setObjectName(_fromUtf8("comboBoxForcedRotation"))
        self.comboBoxForcedRotation.addItem(_fromUtf8(""))
        self.comboBoxForcedRotation.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.comboBoxForcedRotation, 6, 1, 1, 1)
        self.label_05 = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_05.sizePolicy().hasHeightForWidth())
        self.label_05.setSizePolicy(sizePolicy)
        self.label_05.setMinimumSize(QtCore.QSize(0, 0))
        self.label_05.setMaximumSize(QtCore.QSize(16777215, 55))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(50)
        font.setBold(False)
        self.label_05.setFont(font)
        self.label_05.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_05.setObjectName(_fromUtf8("label_05"))
        self.gridLayout_2.addWidget(self.label_05, 9, 0, 1, 1)
        self.comboBoxTactile = QtGui.QComboBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxTactile.sizePolicy().hasHeightForWidth())
        self.comboBoxTactile.setSizePolicy(sizePolicy)
        self.comboBoxTactile.setMinimumSize(QtCore.QSize(0, 55))
        self.comboBoxTactile.setMaximumSize(QtCore.QSize(16777215, 55))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.comboBoxTactile.setFont(font)
        self.comboBoxTactile.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBoxTactile.setMaxVisibleItems(2)
        self.comboBoxTactile.setMaxCount(2)
        self.comboBoxTactile.setObjectName(_fromUtf8("comboBoxTactile"))
        self.comboBoxTactile.addItem(_fromUtf8(""))
        self.comboBoxTactile.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.comboBoxTactile, 9, 1, 1, 1)
        self.label_06 = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_06.sizePolicy().hasHeightForWidth())
        self.label_06.setSizePolicy(sizePolicy)
        self.label_06.setMinimumSize(QtCore.QSize(0, 0))
        self.label_06.setMaximumSize(QtCore.QSize(16777215, 55))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(50)
        font.setBold(False)
        self.label_06.setFont(font)
        self.label_06.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_06.setObjectName(_fromUtf8("label_06"))
        self.gridLayout_2.addWidget(self.label_06, 10, 0, 1, 1)
        self.comboBoxZoomPress = QtGui.QComboBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxZoomPress.sizePolicy().hasHeightForWidth())
        self.comboBoxZoomPress.setSizePolicy(sizePolicy)
        self.comboBoxZoomPress.setMinimumSize(QtCore.QSize(0, 55))
        self.comboBoxZoomPress.setMaximumSize(QtCore.QSize(16777215, 55))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.comboBoxZoomPress.setFont(font)
        self.comboBoxZoomPress.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBoxZoomPress.setMaxVisibleItems(2)
        self.comboBoxZoomPress.setMaxCount(2)
        self.comboBoxZoomPress.setObjectName(_fromUtf8("comboBoxZoomPress"))
        self.comboBoxZoomPress.addItem(_fromUtf8(""))
        self.comboBoxZoomPress.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.comboBoxZoomPress, 10, 1, 1, 1)
        self.label_07 = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_07.sizePolicy().hasHeightForWidth())
        self.label_07.setSizePolicy(sizePolicy)
        self.label_07.setMinimumSize(QtCore.QSize(0, 0))
        self.label_07.setMaximumSize(QtCore.QSize(16777215, 55))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(50)
        font.setBold(False)
        self.label_07.setFont(font)
        self.label_07.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_07.setObjectName(_fromUtf8("label_07"))
        self.gridLayout_2.addWidget(self.label_07, 11, 0, 1, 1)
        self.doubleSpinBoxParallax = QtGui.QDoubleSpinBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBoxParallax.sizePolicy().hasHeightForWidth())
        self.doubleSpinBoxParallax.setSizePolicy(sizePolicy)
        self.doubleSpinBoxParallax.setMinimumSize(QtCore.QSize(0, 55))
        self.doubleSpinBoxParallax.setMaximumSize(QtCore.QSize(16777215, 55))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setWeight(50)
        font.setBold(False)
        self.doubleSpinBoxParallax.setFont(font)
        self.doubleSpinBoxParallax.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBoxParallax.setDecimals(1)
        self.doubleSpinBoxParallax.setMinimum(-100.0)
        self.doubleSpinBoxParallax.setMaximum(100.0)
        self.doubleSpinBoxParallax.setSingleStep(0.1)
        self.doubleSpinBoxParallax.setProperty(_fromUtf8("value"), 1.3)
        self.doubleSpinBoxParallax.setObjectName(_fromUtf8("doubleSpinBoxParallax"))
        self.gridLayout_2.addWidget(self.doubleSpinBoxParallax, 11, 1, 1, 1)
        self.label_08 = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_08.sizePolicy().hasHeightForWidth())
        self.label_08.setSizePolicy(sizePolicy)
        self.label_08.setMinimumSize(QtCore.QSize(0, 0))
        self.label_08.setMaximumSize(QtCore.QSize(16777215, 55))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(50)
        font.setBold(False)
        self.label_08.setFont(font)
        self.label_08.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_08.setObjectName(_fromUtf8("label_08"))
        self.gridLayout_2.addWidget(self.label_08, 13, 0, 1, 1)
        self.comboBoxFMTX = QtGui.QComboBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxFMTX.sizePolicy().hasHeightForWidth())
        self.comboBoxFMTX.setSizePolicy(sizePolicy)
        self.comboBoxFMTX.setMinimumSize(QtCore.QSize(0, 55))
        self.comboBoxFMTX.setMaximumSize(QtCore.QSize(16777215, 55))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.comboBoxFMTX.setFont(font)
        self.comboBoxFMTX.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBoxFMTX.setMaxVisibleItems(2)
        self.comboBoxFMTX.setMaxCount(2)
        self.comboBoxFMTX.setObjectName(_fromUtf8("comboBoxFMTX"))
        self.comboBoxFMTX.addItem(_fromUtf8(""))
        self.comboBoxFMTX.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.comboBoxFMTX, 13, 1, 1, 1)
        self.label_09 = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_09.sizePolicy().hasHeightForWidth())
        self.label_09.setSizePolicy(sizePolicy)
        self.label_09.setMinimumSize(QtCore.QSize(0, 0))
        self.label_09.setMaximumSize(QtCore.QSize(16777215, 55))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(50)
        font.setBold(False)
        self.label_09.setFont(font)
        self.label_09.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_09.setObjectName(_fromUtf8("label_09"))
        self.gridLayout_2.addWidget(self.label_09, 16, 0, 1, 1)
        self.comboBoxAppMenuEditor = QtGui.QComboBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxAppMenuEditor.sizePolicy().hasHeightForWidth())
        self.comboBoxAppMenuEditor.setSizePolicy(sizePolicy)
        self.comboBoxAppMenuEditor.setMinimumSize(QtCore.QSize(0, 55))
        self.comboBoxAppMenuEditor.setMaximumSize(QtCore.QSize(16777215, 55))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.comboBoxAppMenuEditor.setFont(font)
        self.comboBoxAppMenuEditor.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBoxAppMenuEditor.setMaxVisibleItems(2)
        self.comboBoxAppMenuEditor.setMaxCount(2)
        self.comboBoxAppMenuEditor.setObjectName(_fromUtf8("comboBoxAppMenuEditor"))
        self.comboBoxAppMenuEditor.addItem(_fromUtf8(""))
        self.comboBoxAppMenuEditor.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.comboBoxAppMenuEditor, 16, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(0, 0))
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 55))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(50)
        font.setBold(False)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 17, 0, 1, 1)
        self.comboBoxDesktopEditor = QtGui.QComboBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxDesktopEditor.sizePolicy().hasHeightForWidth())
        self.comboBoxDesktopEditor.setSizePolicy(sizePolicy)
        self.comboBoxDesktopEditor.setMinimumSize(QtCore.QSize(0, 55))
        self.comboBoxDesktopEditor.setMaximumSize(QtCore.QSize(16777215, 55))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.comboBoxDesktopEditor.setFont(font)
        self.comboBoxDesktopEditor.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBoxDesktopEditor.setMaxVisibleItems(2)
        self.comboBoxDesktopEditor.setMaxCount(2)
        self.comboBoxDesktopEditor.setObjectName(_fromUtf8("comboBoxDesktopEditor"))
        self.comboBoxDesktopEditor.addItem(_fromUtf8(""))
        self.comboBoxDesktopEditor.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.comboBoxDesktopEditor, 17, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMinimumSize(QtCore.QSize(0, 0))
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 55))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(50)
        font.setBold(False)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 20, 0, 1, 1)
        self.doubleSpinBoxRowsStatusMenu = QtGui.QDoubleSpinBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBoxRowsStatusMenu.sizePolicy().hasHeightForWidth())
        self.doubleSpinBoxRowsStatusMenu.setSizePolicy(sizePolicy)
        self.doubleSpinBoxRowsStatusMenu.setMinimumSize(QtCore.QSize(0, 55))
        self.doubleSpinBoxRowsStatusMenu.setMaximumSize(QtCore.QSize(16777215, 55))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setWeight(50)
        font.setBold(False)
        self.doubleSpinBoxRowsStatusMenu.setFont(font)
        self.doubleSpinBoxRowsStatusMenu.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBoxRowsStatusMenu.setDecimals(0)
        self.doubleSpinBoxRowsStatusMenu.setMinimum(1.0)
        self.doubleSpinBoxRowsStatusMenu.setMaximum(7.0)
        self.doubleSpinBoxRowsStatusMenu.setSingleStep(1.0)
        self.doubleSpinBoxRowsStatusMenu.setProperty(_fromUtf8("value"), 6.0)
        self.doubleSpinBoxRowsStatusMenu.setObjectName(_fromUtf8("doubleSpinBoxRowsStatusMenu"))
        self.gridLayout_2.addWidget(self.doubleSpinBoxRowsStatusMenu, 20, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMinimumSize(QtCore.QSize(0, 0))
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 55))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(50)
        font.setBold(False)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_2.addWidget(self.label_12, 21, 0, 1, 1)
        self.doubleSpinBoxRowsStatusMenuPortrait = QtGui.QDoubleSpinBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBoxRowsStatusMenuPortrait.sizePolicy().hasHeightForWidth())
        self.doubleSpinBoxRowsStatusMenuPortrait.setSizePolicy(sizePolicy)
        self.doubleSpinBoxRowsStatusMenuPortrait.setMinimumSize(QtCore.QSize(0, 55))
        self.doubleSpinBoxRowsStatusMenuPortrait.setMaximumSize(QtCore.QSize(16777215, 55))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setWeight(50)
        font.setBold(False)
        self.doubleSpinBoxRowsStatusMenuPortrait.setFont(font)
        self.doubleSpinBoxRowsStatusMenuPortrait.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBoxRowsStatusMenuPortrait.setDecimals(0)
        self.doubleSpinBoxRowsStatusMenuPortrait.setMinimum(1.0)
        self.doubleSpinBoxRowsStatusMenuPortrait.setMaximum(11.0)
        self.doubleSpinBoxRowsStatusMenuPortrait.setSingleStep(1.0)
        self.doubleSpinBoxRowsStatusMenuPortrait.setProperty(_fromUtf8("value"), 8.0)
        self.doubleSpinBoxRowsStatusMenuPortrait.setObjectName(_fromUtf8("doubleSpinBoxRowsStatusMenuPortrait"))
        self.gridLayout_2.addWidget(self.doubleSpinBoxRowsStatusMenuPortrait, 21, 1, 1, 1)
        self.label_01 = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_01.sizePolicy().hasHeightForWidth())
        self.label_01.setSizePolicy(sizePolicy)
        self.label_01.setMinimumSize(QtCore.QSize(0, 0))
        self.label_01.setMaximumSize(QtCore.QSize(16777215, 55))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(50)
        font.setBold(False)
        self.label_01.setFont(font)
        self.label_01.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_01.setObjectName(_fromUtf8("label_01"))
        self.gridLayout_2.addWidget(self.label_01, 0, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setMinimumSize(QtCore.QSize(0, 55))
        self.label_13.setMaximumSize(QtCore.QSize(16777215, 55))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_2.addWidget(self.label_13, 18, 0, 1, 2)
        self.label_14 = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setMinimumSize(QtCore.QSize(0, 55))
        self.label_14.setMaximumSize(QtCore.QSize(16777215, 55))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_2.addWidget(self.label_14, 14, 0, 1, 2)
        self.label_17 = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setMinimumSize(QtCore.QSize(0, 55))
        self.label_17.setMaximumSize(QtCore.QSize(16777215, 55))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_2.addWidget(self.label_17, 3, 0, 1, 2)
        self.line_01 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.line_01.setStyleSheet(_fromUtf8(""))
        self.line_01.setLineWidth(3)
        self.line_01.setMidLineWidth(3)
        self.line_01.setFrameShape(QtGui.QFrame.HLine)
        self.line_01.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_01.setObjectName(_fromUtf8("line_01"))
        self.gridLayout_2.addWidget(self.line_01, 15, 0, 1, 2)
        self.line_3 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.line_3.setStyleSheet(_fromUtf8(""))
        self.line_3.setLineWidth(3)
        self.line_3.setMidLineWidth(3)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout_2.addWidget(self.line_3, 19, 0, 1, 2)
        self.line_4 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.line_4.setStyleSheet(_fromUtf8(""))
        self.line_4.setLineWidth(3)
        self.line_4.setMidLineWidth(3)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.gridLayout_2.addWidget(self.line_4, 8, 0, 1, 2)
        self.label_18 = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setMinimumSize(QtCore.QSize(0, 60))
        self.label_18.setMaximumSize(QtCore.QSize(16777215, 55))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_2.addWidget(self.label_18, 7, 0, 1, 2)
        self.line_5 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.line_5.setStyleSheet(_fromUtf8(""))
        self.line_5.setLineWidth(3)
        self.line_5.setMidLineWidth(3)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.gridLayout_2.addWidget(self.line_5, 4, 0, 1, 2)
        self.label_19 = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setMinimumSize(QtCore.QSize(0, 0))
        self.label_19.setMaximumSize(QtCore.QSize(16777215, 55))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(50)
        font.setBold(False)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_2.addWidget(self.label_19, 1, 0, 1, 1)
        self.comboBoxBlurlessSaturation = QtGui.QComboBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxBlurlessSaturation.sizePolicy().hasHeightForWidth())
        self.comboBoxBlurlessSaturation.setSizePolicy(sizePolicy)
        self.comboBoxBlurlessSaturation.setMinimumSize(QtCore.QSize(0, 55))
        self.comboBoxBlurlessSaturation.setMaximumSize(QtCore.QSize(16777215, 55))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.comboBoxBlurlessSaturation.setFont(font)
        self.comboBoxBlurlessSaturation.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBoxBlurlessSaturation.setMaxVisibleItems(2)
        self.comboBoxBlurlessSaturation.setMaxCount(2)
        self.comboBoxBlurlessSaturation.setObjectName(_fromUtf8("comboBoxBlurlessSaturation"))
        self.comboBoxBlurlessSaturation.addItem(_fromUtf8(""))
        self.comboBoxBlurlessSaturation.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.comboBoxBlurlessSaturation, 1, 1, 1, 1)
        self.label_15 = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setMinimumSize(QtCore.QSize(0, 0))
        self.label_15.setMaximumSize(QtCore.QSize(16777215, 55))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(50)
        font.setBold(False)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_2.addWidget(self.label_15, 12, 0, 1, 1)
        self.comboBoxDesktopScroll = QtGui.QComboBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxDesktopScroll.sizePolicy().hasHeightForWidth())
        self.comboBoxDesktopScroll.setSizePolicy(sizePolicy)
        self.comboBoxDesktopScroll.setMinimumSize(QtCore.QSize(0, 55))
        self.comboBoxDesktopScroll.setMaximumSize(QtCore.QSize(16777215, 55))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.comboBoxDesktopScroll.setFont(font)
        self.comboBoxDesktopScroll.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBoxDesktopScroll.setMaxVisibleItems(2)
        self.comboBoxDesktopScroll.setMaxCount(2)
        self.comboBoxDesktopScroll.setObjectName(_fromUtf8("comboBoxDesktopScroll"))
        self.comboBoxDesktopScroll.addItem(_fromUtf8(""))
        self.comboBoxDesktopScroll.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.comboBoxDesktopScroll, 12, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 1, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 3)
        self.btnSetCurrent = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSetCurrent.sizePolicy().hasHeightForWidth())
        self.btnSetCurrent.setSizePolicy(sizePolicy)
        self.btnSetCurrent.setMaximumSize(QtCore.QSize(16777215, 55))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.btnSetCurrent.setFont(font)
        self.btnSetCurrent.setToolTip(_fromUtf8(""))
        self.btnSetCurrent.setStatusTip(_fromUtf8(""))
        self.btnSetCurrent.setWhatsThis(_fromUtf8(""))
        self.btnSetCurrent.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.btnSetCurrent.setProperty(_fromUtf8("accessibleName"), _fromUtf8(""))
        self.btnSetCurrent.setProperty(_fromUtf8("accessibleDescription"), _fromUtf8(""))
        self.btnSetCurrent.setObjectName(_fromUtf8("btnSetCurrent"))
        self.gridLayout_3.addWidget(self.btnSetCurrent, 2, 0, 1, 1)
        self.btnSetDefault = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSetDefault.sizePolicy().hasHeightForWidth())
        self.btnSetDefault.setSizePolicy(sizePolicy)
        self.btnSetDefault.setMaximumSize(QtCore.QSize(16777215, 55))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.btnSetDefault.setFont(font)
        self.btnSetDefault.setToolTip(_fromUtf8(""))
        self.btnSetDefault.setStatusTip(_fromUtf8(""))
        self.btnSetDefault.setWhatsThis(_fromUtf8(""))
        self.btnSetDefault.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.btnSetDefault.setProperty(_fromUtf8("accessibleName"), _fromUtf8(""))
        self.btnSetDefault.setProperty(_fromUtf8("accessibleDescription"), _fromUtf8(""))
        self.btnSetDefault.setObjectName(_fromUtf8("btnSetDefault"))
        self.gridLayout_3.addWidget(self.btnSetDefault, 2, 1, 1, 1)
        self.btnCreateConfig = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCreateConfig.sizePolicy().hasHeightForWidth())
        self.btnCreateConfig.setSizePolicy(sizePolicy)
        self.btnCreateConfig.setMaximumSize(QtCore.QSize(16777215, 55))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.btnCreateConfig.setFont(font)
        self.btnCreateConfig.setToolTip(_fromUtf8(""))
        self.btnCreateConfig.setStatusTip(_fromUtf8(""))
        self.btnCreateConfig.setWhatsThis(_fromUtf8(""))
        self.btnCreateConfig.setStyleSheet(_fromUtf8("color: rgb(255, 0, 0);"))
        self.btnCreateConfig.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.btnCreateConfig.setProperty(_fromUtf8("accessibleName"), _fromUtf8(""))
        self.btnCreateConfig.setProperty(_fromUtf8("accessibleDescription"), _fromUtf8(""))
        self.btnCreateConfig.setObjectName(_fromUtf8("btnCreateConfig"))
        self.gridLayout_3.addWidget(self.btnCreateConfig, 2, 2, 1, 1)
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setStyleSheet(_fromUtf8("color: rgb(255, 0, 0);\n"
"selection-color: rgb(255, 0, 0);\n"
"selection-background-color: rgb(255, 0, 0);\n"
"selection-color: rgb(255, 0, 0);\n"
"alternate-background-color: rgb(255, 0, 0);\n"
"gridline-color: rgb(255, 0, 0);\n"
"background-color: rgb(255, 0, 0);"))
        self.line_2.setFrameShadow(QtGui.QFrame.Plain)
        self.line_2.setLineWidth(2)
        self.line_2.setMidLineWidth(0)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout_3.addWidget(self.line_2, 1, 0, 1, 3)
        CSSUfeaturesUI.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(CSSUfeaturesUI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuQuit = QtGui.QMenu(self.menubar)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menuQuit.sizePolicy().hasHeightForWidth())
        self.menuQuit.setSizePolicy(sizePolicy)
        self.menuQuit.setObjectName(_fromUtf8("menuQuit"))
        CSSUfeaturesUI.setMenuBar(self.menubar)
        self.actionQuit = QtGui.QAction(CSSUfeaturesUI)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionAbout = QtGui.QAction(CSSUfeaturesUI)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionRestoreDefaults = QtGui.QAction(CSSUfeaturesUI)
        self.actionRestoreDefaults.setObjectName(_fromUtf8("actionRestoreDefaults"))
        self.actionRebootDevice = QtGui.QAction(CSSUfeaturesUI)
        self.actionRebootDevice.setObjectName(_fromUtf8("actionRebootDevice"))
        self.actionAddPowerKeyEntry = QtGui.QAction(CSSUfeaturesUI)
        self.actionAddPowerKeyEntry.setObjectName(_fromUtf8("actionAddPowerKeyEntry"))
        self.actionRemovePowerKeyEntry = QtGui.QAction(CSSUfeaturesUI)
        self.actionRemovePowerKeyEntry.setObjectName(_fromUtf8("actionRemovePowerKeyEntry"))
        self.menuQuit.addAction(self.actionRestoreDefaults)
        self.menuQuit.addAction(self.actionAddPowerKeyEntry)
        self.menuQuit.addAction(self.actionRemovePowerKeyEntry)
        self.menuQuit.addAction(self.actionRebootDevice)
        self.menuQuit.addSeparator()
        self.menuQuit.addAction(self.actionAbout)
        self.menuQuit.addAction(self.actionQuit)
        self.menubar.addAction(self.menuQuit.menuAction())

        self.retranslateUi(CSSUfeaturesUI)
        QtCore.QMetaObject.connectSlotsByName(CSSUfeaturesUI)

    def retranslateUi(self, CSSUfeaturesUI):
        CSSUfeaturesUI.setWindowTitle(QtGui.QApplication.translate("CSSUfeaturesUI", "CSSU Features Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxBlurless.setItemText(0, QtGui.QApplication.translate("CSSUfeaturesUI", "Maemo Style (default)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxBlurless.setItemText(1, QtGui.QApplication.translate("CSSUfeaturesUI", "Meego/Symbian Style", None, QtGui.QApplication.UnicodeUTF8))
        self.label_02.setText(QtGui.QApplication.translate("CSSUfeaturesUI", "Task Switcher", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxTaskSwitcher.setItemText(0, QtGui.QApplication.translate("CSSUfeaturesUI", "Maemo Style (default)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxTaskSwitcher.setItemText(1, QtGui.QApplication.translate("CSSUfeaturesUI", "Bigger-One column", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxTaskSwitcher.setItemText(2, QtGui.QApplication.translate("CSSUfeaturesUI", "Bigger-Two columns", None, QtGui.QApplication.UnicodeUTF8))
        self.label_03.setText(QtGui.QApplication.translate("CSSUfeaturesUI", "Around Axis", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxRotationAxis.setItemText(0, QtGui.QApplication.translate("CSSUfeaturesUI", "X/Y (default)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxRotationAxis.setItemText(1, QtGui.QApplication.translate("CSSUfeaturesUI", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.label_04.setText(QtGui.QApplication.translate("CSSUfeaturesUI", "Applications", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxForcedRotation.setItemText(0, QtGui.QApplication.translate("CSSUfeaturesUI", "Auto (default)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxForcedRotation.setItemText(1, QtGui.QApplication.translate("CSSUfeaturesUI", "Forced", None, QtGui.QApplication.UnicodeUTF8))
        self.label_05.setText(QtGui.QApplication.translate("CSSUfeaturesUI", "Tactile Feedback", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxTactile.setItemText(0, QtGui.QApplication.translate("CSSUfeaturesUI", "Disabled (default)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxTactile.setItemText(1, QtGui.QApplication.translate("CSSUfeaturesUI", "Enabled", None, QtGui.QApplication.UnicodeUTF8))
        self.label_06.setText(QtGui.QApplication.translate("CSSUfeaturesUI", "Zoom on Press", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxZoomPress.setItemText(0, QtGui.QApplication.translate("CSSUfeaturesUI", "Disabled (default)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxZoomPress.setItemText(1, QtGui.QApplication.translate("CSSUfeaturesUI", "Enabled", None, QtGui.QApplication.UnicodeUTF8))
        self.label_07.setText(QtGui.QApplication.translate("CSSUfeaturesUI", "Parallax", None, QtGui.QApplication.UnicodeUTF8))
        self.label_08.setText(QtGui.QApplication.translate("CSSUfeaturesUI", "FMTX applet", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxFMTX.setItemText(0, QtGui.QApplication.translate("CSSUfeaturesUI", "Auto (default)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxFMTX.setItemText(1, QtGui.QApplication.translate("CSSUfeaturesUI", "Always Visible", None, QtGui.QApplication.UnicodeUTF8))
        self.label_09.setText(QtGui.QApplication.translate("CSSUfeaturesUI", "Application menu", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxAppMenuEditor.setItemText(0, QtGui.QApplication.translate("CSSUfeaturesUI", "Allowed (default)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxAppMenuEditor.setItemText(1, QtGui.QApplication.translate("CSSUfeaturesUI", "Disabled", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("CSSUfeaturesUI", "Desktop menu", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxDesktopEditor.setItemText(0, QtGui.QApplication.translate("CSSUfeaturesUI", "Allowed (default)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxDesktopEditor.setItemText(1, QtGui.QApplication.translate("CSSUfeaturesUI", "Disabled", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("CSSUfeaturesUI", "Landscape", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("CSSUfeaturesUI", "Portrait", None, QtGui.QApplication.UnicodeUTF8))
        self.label_01.setText(QtGui.QApplication.translate("CSSUfeaturesUI", "Blurless", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("CSSUfeaturesUI", " Status menu rows:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("CSSUfeaturesUI", " Edit mode:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("CSSUfeaturesUI", " Rotation:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("CSSUfeaturesUI", " General:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("CSSUfeaturesUI", "Blurless Saturation", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxBlurlessSaturation.setItemText(0, QtGui.QApplication.translate("CSSUfeaturesUI", "No Color (default)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxBlurlessSaturation.setItemText(1, QtGui.QApplication.translate("CSSUfeaturesUI", "Full Color", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("CSSUfeaturesUI", "Desktop Scroll", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxDesktopScroll.setItemText(0, QtGui.QApplication.translate("CSSUfeaturesUI", "Horizontal (default)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxDesktopScroll.setItemText(1, QtGui.QApplication.translate("CSSUfeaturesUI", "Vertical", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSetCurrent.setText(QtGui.QApplication.translate("CSSUfeaturesUI", "Current", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSetDefault.setText(QtGui.QApplication.translate("CSSUfeaturesUI", "Default", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCreateConfig.setText(QtGui.QApplication.translate("CSSUfeaturesUI", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.menuQuit.setTitle(QtGui.QApplication.translate("CSSUfeaturesUI", "Main", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("CSSUfeaturesUI", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("CSSUfeaturesUI", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRestoreDefaults.setText(QtGui.QApplication.translate("CSSUfeaturesUI", "Restore Defaults", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRebootDevice.setText(QtGui.QApplication.translate("CSSUfeaturesUI", "Reboot Device", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAddPowerKeyEntry.setText(QtGui.QApplication.translate("CSSUfeaturesUI", "Add PowerKey Entry", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRemovePowerKeyEntry.setText(QtGui.QApplication.translate("CSSUfeaturesUI", "Remove PowerKey Entry", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    CSSUfeaturesUI = QtGui.QMainWindow()
    ui = Ui_CSSUfeaturesUI()
    ui.setupUi(CSSUfeaturesUI)
    CSSUfeaturesUI.show()
    sys.exit(app.exec_())

